services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: swapi_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  swapi_scraper:
    image: tudor0h/swapi_scraper:latest
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/swapi_db
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: